Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import statsmodels.api as sm

sm_model = sm.Logit.from_formula('default ~ balance + income + student', data=df)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_1809/711570277.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mstatsmodels[0m[0;34m.[0m[0mapi[0m [0;32mas[0m [0msm[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0msm_model[0m [0;34m=[0m [0msm[0m[0;34m.[0m[0mLogit[0m[0;34m.[0m[0mfrom_formula[0m[0;34m([0m[0;34m'default ~ balance + income + student'[0m[0;34m,[0m [0mdata[0m[0;34m=[0m[0mdf[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/statsmodels/base/model.py[0m in [0;36mfrom_formula[0;34m(cls, formula, data, subset, drop_cols, *args, **kwargs)[0m
[1;32m    207[0m                              [0;34m'columns that has shape {0}. This occurs when '[0m[0;34m[0m[0;34m[0m[0m
[1;32m    208[0m                              [0;34m'the variable converted to endog is non-numeric'[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 209[0;31m                              ' (e.g., bool or str).'.format(endog.shape))
[0m[1;32m    210[0m         [0;32mif[0m [0mdrop_cols[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m [0;32mand[0m [0mlen[0m[0;34m([0m[0mdrop_cols[0m[0;34m)[0m [0;34m>[0m [0;36m0[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    211[0m             [0mcols[0m [0;34m=[0m [0;34m[[0m[0mx[0m [0;32mfor[0m [0mx[0m [0;32min[0m [0mexog[0m[0;34m.[0m[0mcolumns[0m [0;32mif[0m [0mx[0m [0;32mnot[0m [0;32min[0m [0mdrop_cols[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mValueError[0m: endog has evaluated to an array with multiple columns that has shape (10000, 2). This occurs when the variable converted to endog is non-numeric (e.g., bool or str).
ValueError: endog has evaluated to an array with multiple columns that has shape (10000, 2). This occurs when the variable converted to endog is non-numeric (e.g., bool or str).

